services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}-web
    build: .
    command: python3 app/main.py
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery-main:
    container_name: ${COMPOSE_PROJECT_NAME}-celery-main
    build: .
    command: celery -A app.celery.celery_app worker -l info
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    image: rabbitmq:4.0-management
    volumes:
      - rabbimq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_NODE_PORT=${RABBITMQ_PORT}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
    ports:
      - 15672:15672

  celery-flower:
    container_name: ${COMPOSE_PROJECT_NAME}-celery-flower
    build: .
    command: celery -A app.celery.celery_app flower
    environment:
      - FLOWER_UNAUTHENTICATED_API=true
    ports:
      - 5555:5555
    depends_on:
      rabbitmq:
        condition: service_healthy


volumes:
  rabbimq_data:
    name: ${COMPOSE_PROJECT_NAME}_rabbimq_data
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME}_postgres_data
